# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseplate',
            name='expiration_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='emissions_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='retire_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='safety_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='effective_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='expiration_date',
            field=models.DateField(blank=True),
        ),
    ]
