# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170518_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='warranty',
            name='name',
            field=models.CharField(default='None', max_length=16),
        ),
    ]
