# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_warranty_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='retire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
