# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 02:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170518_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=64)),
                ('tax_identifier', models.CharField(max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_address', to='app.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('relationship', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_phone', models.CharField(max_length=16)),
                ('seondary_phone', models.CharField(blank=True, max_length=16)),
                ('email_address', models.CharField(blank=True, max_length=64)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_address', to='app.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('middle_name', models.CharField(blank=True, max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('is_available', models.BooleanField(default=True)),
                ('start_date', models.DateField(null=True)),
                ('terminate_date', models.DateField(null=True)),
                ('notes', models.TextField(blank=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_address', to='app.Address')),
                ('assigned_truck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_truck', to='app.Truck')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_company', to='app.Company')),
                ('contact_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_contact_info', to='app.ContactInfo')),
            ],
        ),
        migrations.CreateModel(
            name='DrivingLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16)),
                ('lic_class', models.CharField(max_length=16)),
                ('issue_state', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='PayRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PH', 'Hourly'), ('PM', 'Per Mile')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='driving_license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license', to='app.DrivingLicense'),
        ),
        migrations.AddField(
            model_name='driver',
            name='emergency_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contact', to='app.Contact'),
        ),
        migrations.AddField(
            model_name='driver',
            name='pay_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='app.PayRate'),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='app.ContactInfo'),
        ),
    ]
