# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170518_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrate',
            name='pay_rate',
            field=models.DecimalField(decimal_places=2, default=0.4, max_digits=6, verbose_name='Rate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payrate',
            name='type',
            field=models.CharField(choices=[('Per Hour', 'Hourly'), ('Per Mile', 'Per Mile')], max_length=8),
        ),
    ]
