# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170518_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='address',
        ),
        migrations.AddField(
            model_name='drivinglicense',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drivinglicense',
            name='expiration_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drivinglicense',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email_address',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='driver',
            name='start_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='terminate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licenseplate',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payrate',
            name='type',
            field=models.CharField(choices=[('Per Hour', 'Hourly'), ('Per Mile', 'Per Mile'), ('Other', 'Other')], max_length=8),
        ),
    ]
