# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 14:53
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170519_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='primary_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='seondary_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='warrantyadmin',
            name='fax',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='warrantyadmin',
            name='primary_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='warrantyadmin',
            name='secondary_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True),
        ),
    ]
