# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170519_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadIncident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('total_mileage', models.DecimalField(decimal_places=2, max_digits=7)),
                ('status', models.IntegerField(choices=[(1, 'Planned'), (2, 'In Progress'), (3, 'Complete'), (4, 'Canceled')], default=1)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address_line_1', models.CharField(max_length=64)),
                ('address_line_2', models.CharField(blank=True, max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=16)),
                ('postal_code', models.CharField(blank=True, max_length=16)),
                ('country', models.CharField(max_length=16)),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='stops',
            field=models.ManyToManyField(to='app.Waypoint'),
        ),
        migrations.AddField(
            model_name='trip',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truck', to='app.Truck'),
        ),
        migrations.AddField(
            model_name='roadincident',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_trip', to='app.Trip'),
        ),
    ]
