# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20170522_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='odometer',
            field=models.ManyToManyField(null=True, to='app.Odometer'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='warranties',
            field=models.ManyToManyField(null=True, to='app.Warranty'),
        ),
    ]
