# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20170522_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='warrantyadmin',
            name='address',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address_line_1',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='country',
            field=models.CharField(default='USA', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='postal_code',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='state',
            field=models.CharField(default='ON', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='employment_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employment_reference', to='app.Contact'),
        ),
        migrations.AddField(
            model_name='roadincident',
            name='incident_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warrantyadmin',
            name='address_line_1',
            field=models.CharField(default=' aa ', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warrantyadmin',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='warrantyadmin',
            name='city',
            field=models.CharField(default='Brampton', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warrantyadmin',
            name='country',
            field=models.CharField(default='Canada', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warrantyadmin',
            name='postal_code',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='warrantyadmin',
            name='state',
            field=models.CharField(default='ON', max_length=16),
            preserve_default=False,
        ),
    ]
