# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20170524_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.AddField(
            model_name='company',
            name='address_line_1',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='postal_code',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='truck',
            name='odometer',
            field=models.ManyToManyField(to='app.Odometer'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='warranties',
            field=models.ManyToManyField(to='app.Warranty'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='warranty_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_admin', to='app.WarrantyAdmin'),
        ),
    ]
