# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20170524_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='driver',
            name='pay_rate',
        ),
        migrations.AddField(
            model_name='driverpay',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='app.Driver'),
        ),
        migrations.AddField(
            model_name='driverpay',
            name='rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='app.PayRate'),
        ),
    ]
