# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20170524_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roadincident',
            old_name='incident_dt',
            new_name='incident_date_time',
        ),
        migrations.RemoveField(
            model_name='driverpay',
            name='driver',
        ),
        migrations.AddField(
            model_name='driver',
            name='pay_rate',
            field=models.ManyToManyField(to='app.DriverPay'),
        ),
    ]
