# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_trip_drivers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='pay_rate',
        ),
        migrations.AddField(
            model_name='driver',
            name='pay_rate',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='driver_pay_rate', to='app.DriverPay'),
            preserve_default=False,
        ),
    ]
