# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20170525_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
